[package]
name = "tmp_guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tmp_guest"
path = "./src/lib.rs"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", git = "https://github.com/a16z/jolt", version = "0.1.0"  }
