[package]
name = "zkRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
sp1-core = { git = "https://github.com/succinctlabs/sp1.git", tag = "v0.0.2" }
time = "0.3.35"
