[package]
name = "zkRust"
version = "0.1.0"
edition = "2021"
[features]
nightly = []

[workspace]
members = ["guest"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
sp1-core = { git = "https://github.com/succinctlabs/sp1.git", tag = "v0.0.2" }
jolt = { package = "jolt-sdk", git = "https://github.com/a16z/jolt", features = ["host"] }
regex = "1.10.4"
nom = "7.1.3"
bytes = "1.6.0"
target-lexicon = "0.12.14"
guest = { path = "./guest" }

[patch.crates-io]
ark-ff = { git = "https://github.com/a16z/arkworks-algebra", branch = "optimize/field-from-u64" }
ark-ec = { git = "https://github.com/a16z/arkworks-algebra", branch = "optimize/field-from-u64" }
ark-serialize = { git = "https://github.com/a16z/arkworks-algebra", branch = "optimize/field-from-u64" }



